import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CtaBand } from '../shared';

@Component({
  selector: 'app-about-page', imports: [RouterLink, CtaBand],
  template: `<section class="page-hero"><div class="shell"><span class="eyebrow">ABOUT ELITE INNOVATES</span><h1>Technology with <em>purpose.</em></h1><p>We bring ideas, people and technology together to create useful digital products.</p></div></section>
  <section class="section shell story-grid"><div><span class="eyebrow blue">OUR STORY</span><h2>Built for businesses ready to move forward</h2></div><div><p class="lead">Elite Innovates Solutions Private Limited is a technology company based in New Delhi, India.</p><p>We create websites, software, mobile applications, automation systems, WhatsApp business experiences, digital marketing solutions and practical IT services.</p><p>Our work is grounded in a simple belief: technology should make business clearer, faster and more capable. That means listening carefully, choosing the right approach and building with long-term usefulness in mind.</p></div></section>
  <section class="section values-section"><div class="shell"><div class="section-head centered"><span class="eyebrow blue">WHAT GUIDES US</span><h2>Useful work, built together</h2></div><div class="value-grid"><article><b>01</b><h3>Clarity first</h3><p>We turn complex problems into understandable choices and practical plans.</p></article><article><b>02</b><h3>Partnership always</h3><p>We work openly with clients and keep business outcomes in view.</p></article><article><b>03</b><h3>Quality that lasts</h3><p>We build dependable products that can grow with changing needs.</p></article></div></div></section>
  <section class="section shell about-feature"><div class="feature-art"><span></span><span></span><span></span><b>Ideas<br>People<br>Progress</b></div><div><span class="eyebrow blue">WHY ELITE INNOVATES</span><h2>A practical technology partner</h2><p>Our cross-functional approach connects design, engineering, automation and growth. You get a team that can see the complete picture and make every part work together.</p><a routerLink="/services" class="text-link">Explore our services <span>→</span></a></div></section><app-cta />`
})
export class AboutPage {}

@Component({
  selector: 'app-contact-page', imports: [FormsModule],
  template: `<section class="page-hero contact-hero"><div class="shell"><span class="eyebrow">CONTACT US</span><h1>Tell us what you want to <em>build.</em></h1><p>Share a little about your idea, challenge or next stage of growth.</p></div></section>
  <section class="section shell contact-layout"><div class="contact-details"><span class="eyebrow blue">GET IN TOUCH</span><h2>Start a conversation</h2><p>Whether you have a clear brief or an early idea, we’d be glad to hear it.</p><div class="contact-item"><b>Email</b><a href="mailto:info@eliteinnovates.com">info@eliteinnovates.com</a></div><div class="contact-item"><b>Visit us</b><span>Apex Golf, Sec 1<br>New Delhi, INDIA</span></div><div class="contact-note">We usually begin with a short discovery conversation to understand your goals and recommend the right next step.</div></div>
  <form class="contact-form" (ngSubmit)="submit()" #contactForm="ngForm">@if(sent()){<div class="form-success"><b>Thanks for reaching out.</b><p>Your message is ready. Please email any project files to <a href="mailto:info@eliteinnovates.com">info@eliteinnovates.com</a>.</p><button type="button" class="button button-soft" (click)="sent.set(false)">Send another message</button></div>}@else{<div class="field-row"><label>First name<input name="firstName" ngModel required autocomplete="given-name" placeholder="Your first name"></label><label>Last name<input name="lastName" ngModel required autocomplete="family-name" placeholder="Your last name"></label></div><label>Work email<input name="email" ngModel required email autocomplete="email" placeholder="you@company.com"></label><label>What can we help with?<select name="service" ngModel required><option value="" disabled selected>Select a service</option><option>Websites & Software</option><option>Business Automation</option><option>Mobile App Development</option><option>WhatsApp Business Management</option><option>Digital Marketing</option><option>IT Solutions</option></select></label><label>Tell us about your project<textarea name="message" ngModel required rows="6" placeholder="A short summary of your goals, timeline and current challenge"></textarea></label><button class="button button-primary" type="submit" [disabled]="contactForm.invalid">Send enquiry <span>→</span></button><p class="form-fineprint">By submitting, you agree to our privacy policy.</p>}</form></section>`
})
export class ContactPage { sent = signal(false); submit(){ this.sent.set(true); } }

@Component({
  selector: 'app-jobs-page', imports: [],
  template: `<section class="page-hero jobs-hero"><div class="shell"><span class="eyebrow">CAREERS</span><h1>Do work that creates <em>momentum.</em></h1><p>Join a collaborative team solving practical business problems with technology.</p></div></section>
  <section class="section shell"><div class="section-head split"><div><span class="eyebrow blue">OPEN OPPORTUNITIES</span><h2>Grow with Elite Innovates</h2></div><p>We’re always interested in thoughtful designers, engineers, marketers and problem solvers.</p></div><div class="jobs-list"><article><div><span>Engineering</span><h3>Full-stack Developer</h3><p>Angular · APIs · Cloud · New Delhi / Hybrid</p></div><a href="mailto:info@eliteinnovates.com?subject=Application%20-%20Full-stack%20Developer" class="button button-soft">Apply by email →</a></article><article><div><span>Design</span><h3>UI/UX Designer</h3><p>Product design · Design systems · New Delhi / Hybrid</p></div><a href="mailto:info@eliteinnovates.com?subject=Application%20-%20UI%2FUX%20Designer" class="button button-soft">Apply by email →</a></article><article><div><span>Marketing</span><h3>Digital Marketing Specialist</h3><p>Campaigns · Content · Analytics · New Delhi / Hybrid</p></div><a href="mailto:info@eliteinnovates.com?subject=Application%20-%20Digital%20Marketing%20Specialist" class="button button-soft">Apply by email →</a></article></div><p class="jobs-note">Don’t see your role? Introduce yourself at <a href="mailto:info@eliteinnovates.com">info@eliteinnovates.com</a>.</p></section>`
})
export class JobsPage {}

@Component({
  selector: 'app-vision-page', imports: [CtaBand],
  template: `<section class="page-hero vision-hero"><div class="shell"><span class="eyebrow">VISION &amp; MISSION</span><h1>A brighter future, built through <em>useful innovation.</em></h1></div></section><section class="section shell mission-grid"><article><span class="eyebrow blue">OUR VISION</span><h2>Make powerful technology feel practical for every growing business.</h2><p>We envision a world where organizations of every size can use digital tools with confidence to serve customers better and create lasting progress.</p></article><article><span class="eyebrow blue">OUR MISSION</span><h2>Turn ambitious ideas into dependable digital solutions.</h2><p>We combine thoughtful strategy, human-centered design and modern engineering to build products that simplify work, improve experiences and support sustainable growth.</p></article></section><section class="section shell principles"><div class="section-head centered"><span class="eyebrow blue">OUR COMMITMENT</span><h2>How we move toward that future</h2></div><div class="value-grid"><article><b>01</b><h3>Make innovation useful</h3><p>Every technology choice should serve a clear business or human need.</p></article><article><b>02</b><h3>Build for progress</h3><p>We create adaptable foundations that can grow as our clients grow.</p></article><article><b>03</b><h3>Earn trust through action</h3><p>We communicate clearly, deliver responsibly and stand behind our work.</p></article></div></section><app-cta />`
})
export class VisionPage {}

@Component({
  selector: 'app-legal-page',
  template: `<section class="legal-hero"><div class="shell"><span class="eyebrow">LEGAL</span><h1>{{isPrivacy ? 'Privacy Policy' : 'Terms & Conditions'}}</h1><p>Last updated: September 22, 2026</p></div></section><article class="legal-content shell">@if(isPrivacy){<h2>Overview</h2><p>Elite Innovates Solutions Private Limited respects your privacy. This policy explains the types of information we may collect when you use our website or contact us, and how we handle that information.</p><h2>Information we collect</h2><p>We may collect information you choose to provide, including your name, email address, company details and project information. We may also receive basic technical information such as browser type, device type and website usage data.</p><h2>How we use information</h2><p>We use information to respond to enquiries, provide requested services, improve our website, maintain security and meet legal obligations. We do not sell personal information.</p><h2>Sharing and retention</h2><p>Information may be shared with service providers who support our operations, subject to appropriate safeguards. We retain information only as long as reasonably necessary for the purposes described here.</p><h2>Your choices</h2><p>You may request access, correction or deletion of personal information by emailing info@eliteinnovates.com. Some information may be retained where required by law.</p><h2>Contact</h2><p>Questions about privacy can be sent to <a href="mailto:info@eliteinnovates.com">info@eliteinnovates.com</a>.</p>}@else{<h2>Using this website</h2><p>These terms govern your use of the Elite Innovates website. By using the website, you agree to use it lawfully and in a way that does not interfere with its operation or the rights of others.</p><h2>Website content</h2><p>Website content is provided for general information. We aim to keep it accurate and current, but we do not guarantee that all information will always be complete or error-free.</p><h2>Intellectual property</h2><p>Unless stated otherwise, the website, branding, written content and original materials are owned by or licensed to Elite Innovates Solutions Private Limited. They may not be reproduced without permission.</p><h2>Third-party links</h2><p>Our website may link to third-party websites. We are not responsible for their content, availability or privacy practices.</p><h2>Services and projects</h2><p>Specific services, timelines, deliverables and commercial terms are governed by the agreement made for each client engagement.</p><h2>Contact</h2><p>Questions about these terms can be sent to <a href="mailto:info@eliteinnovates.com">info@eliteinnovates.com</a>.</p>}</article>`
})
export class LegalPage { private route = inject(ActivatedRoute); isPrivacy = this.route.snapshot.data['type'] === 'privacy'; }
