import { website } from '../site.data';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { CtaBand } from '../shared';

@Component({
  selector: 'app-about-page', imports: [RouterLink, CtaBand],
  template: `<section class="page-hero"><div class="shell"><span class="eyebrow">{{website.copy.ABOUT_ELITE_INNOVATES}}</span><h1>{{website.copy.Technology_with}}<em>{{website.copy.purpose}}</em></h1><p>{{website.copy.We_bring_ideas_people_and_technology_together_to_create_useful_digital_prod}}</p></div></section>
  <section class="section shell story-grid"><div><span class="eyebrow blue">{{website.copy.OUR_STORY}}</span><h2>{{website.copy.Built_for_businesses_ready_to_move_forward}}</h2></div><div><p class="lead">{{website.copy.Elite_Innovates_Solutions_Private_Limited_is_a_technology_company_based_in_}}</p><p>{{website.copy.We_create_websites_software_mobile_applications_automation_systems_WhatsApp}}</p><p>{{website.copy.Our_work_is_grounded_in_a_simple_belief_technology_should_make_business_cle}}</p></div></section>
  <section class="section values-section"><div class="shell"><div class="section-head centered"><span class="eyebrow blue">{{website.copy.WHAT_GUIDES_US}}</span><h2>{{website.copy.Useful_work_built_together}}</h2></div><div class="value-grid"><article><b>01</b><h3>{{website.copy.Clarity_first}}</h3><p>{{website.copy.We_turn_complex_problems_into_understandable_choices_and_practical_plans}}</p></article><article><b>02</b><h3>{{website.copy.Partnership_always}}</h3><p>{{website.copy.We_work_openly_with_clients_and_keep_business_outcomes_in_view}}</p></article><article><b>03</b><h3>{{website.copy.Quality_that_lasts}}</h3><p>{{website.copy.We_build_dependable_products_that_can_grow_with_changing_needs}}</p></article></div></div></section>
  <section class="section shell about-feature"><div class="feature-art"><span></span><span></span><span></span><b>{{website.copy.Ideas}}<br>{{website.copy.People}}<br>{{website.copy.Progress}}</b></div><div><span class="eyebrow blue">{{website.copy.WHY_ELITE_INNOVATES}}</span><h2>{{website.copy.A_practical_technology_partner}}</h2><p>{{website.copy.Our_cross_functional_approach_connects_design_engineering_automation_and_gr}}</p><a routerLink="/services" class="text-link">{{website.copy.Explore_our_services}}<span>→</span></a></div></section><app-cta />`
})
export class AboutPage { website = website;}

@Component({
  selector: 'app-contact-page', imports: [FormsModule],
  template: `<section class="page-hero contact-hero"><div class="shell"><span class="eyebrow">{{website.copy.CONTACT_US}}</span><h1>{{website.copy.Tell_us_what_you_want_to}}<em>{{website.copy.build}}</em></h1><p>{{website.copy.Share_a_little_about_your_idea_challenge_or_next_stage_of_growth}}</p></div></section>
  <section class="section shell contact-layout"><div class="contact-details"><span class="eyebrow blue">{{website.copy.GET_IN_TOUCH}}</span><h2>{{website.copy.Start_a_conversation_2}}</h2><p>{{website.copy.Whether_you_have_a_clear_brief_or_an_early_idea_we_d_be_glad_to_hear_it}}</p><div class="contact-item"><b>{{website.copy.Email}}</b><a [href]="'mailto:' + website.company.email">{{website.company.email}}</a></div><div class="contact-item"><b>{{website.copy.Visit_us}}</b><span>{{website.copy.Apex_Golf_Sec_1}}<br>{{website.copy.New_Delhi_INDIA}}</span></div><div class="contact-note">{{website.copy.We_usually_begin_with_a_short_discovery_conversation_to_understand_your_goa}}</div></div>
  <form class="contact-form" (ngSubmit)="submit()" #contactForm="ngForm">@if(sent()){<div class="form-success"><b>{{website.copy.Thanks_for_reaching_out}}</b><p>{{website.copy.Your_message_is_ready_Please_email_any_project_files_to}}<a [href]="'mailto:' + website.company.email">{{website.company.email}}</a>.</p><button type="button" class="button button-soft" (click)="sent.set(false)">{{website.copy.Send_another_message}}</button></div>}@else{<div class="field-row"><label>{{website.copy.First_name}}<input name="firstName" ngModel required autocomplete="given-name" [placeholder]="website.copy.Your_first_name"></label><label>{{website.copy.Last_name}}<input name="lastName" ngModel required autocomplete="family-name" [placeholder]="website.copy.Your_last_name"></label></div><label>{{website.copy.Work_email}}<input name="email" ngModel required email autocomplete="email" [placeholder]="website.copy.you_company_com"></label><label>{{website.copy.What_can_we_help_with}}<select name="service" ngModel required><option value="" disabled selected>{{website.copy.Select_a_service}}</option><option>{{website.copy.Websites_Software}}</option><option>{{website.copy.Business_Automation}}</option><option>{{website.copy.Mobile_App_Development}}</option><option>{{website.copy.WhatsApp_Business_Management}}</option><option>{{website.copy.Digital_Marketing}}</option><option>{{website.copy.IT_Solutions}}</option></select></label><label>{{website.copy.Tell_us_about_your_project}}<textarea name="message" ngModel required rows="6" [placeholder]="website.copy.A_short_summary_of_your_goals_timeline_and_current_challenge"></textarea></label><button class="button button-primary" type="submit" [disabled]="contactForm.invalid">{{website.copy.Send_enquiry}}<span>→</span></button><p class="form-fineprint">{{website.copy.By_submitting_you_agree_to_our_privacy_policy}}</p>}</form></section>`
})
export class ContactPage { website = website; sent = signal(false); submit(){ this.sent.set(true); } }

@Component({
  selector: 'app-vision-page', imports: [CtaBand],
  template: `<section class="page-hero vision-hero"><div class="shell"><span class="eyebrow">{{website.copy.VISION_MISSION}}</span><h1>{{website.copy.A_brighter_future_built_through}}<em>{{website.copy.useful_innovation}}</em></h1></div></section><section class="section shell mission-grid"><article><span class="eyebrow blue">{{website.copy.OUR_VISION}}</span><h2>{{website.copy.Make_powerful_technology_feel_practical_for_every_growing_business}}</h2><p>{{website.copy.We_envision_a_world_where_organizations_of_every_size_can_use_digital_tools}}</p></article><article><span class="eyebrow blue">{{website.copy.OUR_MISSION}}</span><h2>{{website.copy.Turn_ambitious_ideas_into_dependable_digital_solutions}}</h2><p>{{website.copy.We_combine_thoughtful_strategy_human_centered_design_and_modern_engineering}}</p></article></section><section class="section shell principles"><div class="section-head centered"><span class="eyebrow blue">{{website.copy.OUR_COMMITMENT}}</span><h2>{{website.copy.How_we_move_toward_that_future}}</h2></div><div class="value-grid"><article><b>01</b><h3>{{website.copy.Make_innovation_useful}}</h3><p>{{website.copy.Every_technology_choice_should_serve_a_clear_business_or_human_need}}</p></article><article><b>02</b><h3>{{website.copy.Build_for_progress}}</h3><p>{{website.copy.We_create_adaptable_foundations_that_can_grow_as_our_clients_grow}}</p></article><article><b>03</b><h3>{{website.copy.Earn_trust_through_action}}</h3><p>{{website.copy.We_communicate_clearly_deliver_responsibly_and_stand_behind_our_work}}</p></article></div></section><app-cta />`
})
export class VisionPage { website = website;}

@Component({
  selector: 'app-legal-page',
  template: `<section class="legal-hero"><div class="shell"><span class="eyebrow">{{website.copy.LEGAL}}</span><h1>{{isPrivacy ? website.copy.Privacy_Policy : website.copy.Terms_Conditions}}</h1><p>{{website.copy.Last_updated_September_22_2026}}</p></div></section><article class="legal-content shell">@if(isPrivacy){<h2>{{website.copy.Overview}}</h2><p>{{website.copy.Elite_Innovates_Solutions_Private_Limited_respects_your_privacy_This_policy}}</p><h2>{{website.copy.Information_we_collect}}</h2><p>{{website.copy.We_may_collect_information_you_choose_to_provide_including_your_name_email_}}</p><h2>{{website.copy.How_we_use_information}}</h2><p>{{website.copy.We_use_information_to_respond_to_enquiries_provide_requested_services_impro}}</p><h2>{{website.copy.Sharing_and_retention}}</h2><p>{{website.copy.Information_may_be_shared_with_service_providers_who_support_our_operations}}</p><h2>{{website.copy.Your_choices}}</h2><p>{{website.copy.You_may_request_access_correction_or_deletion_of_personal_information_by_em}}</p><h2>{{website.copy.Contact}}</h2><p>{{website.copy.Questions_about_privacy_can_be_sent_to}}<a [href]="'mailto:' + website.company.email">{{website.company.email}}</a>.</p>}@else{<h2>{{website.copy.Using_this_website}}</h2><p>{{website.copy.These_terms_govern_your_use_of_the_Elite_Innovates_website_By_using_the_web}}</p><h2>{{website.copy.Website_content}}</h2><p>{{website.copy.Website_content_is_provided_for_general_information_We_aim_to_keep_it_accur}}</p><h2>{{website.copy.Intellectual_property}}</h2><p>{{website.copy.Unless_stated_otherwise_the_website_branding_written_content_and_original_m}}</p><h2>{{website.copy.Third_party_links}}</h2><p>{{website.copy.Our_website_may_link_to_third_party_websites_We_are_not_responsible_for_the}}</p><h2>{{website.copy.Services_and_projects}}</h2><p>{{website.copy.Specific_services_timelines_deliverables_and_commercial_terms_are_governed_}}</p><h2>{{website.copy.Contact}}</h2><p>{{website.copy.Questions_about_these_terms_can_be_sent_to}}<a [href]="'mailto:' + website.company.email">{{website.company.email}}</a>.</p>}</article>`
})
export class LegalPage { website = website; private route = inject(ActivatedRoute); isPrivacy = this.route.snapshot.data['type'] === 'privacy'; }
